name: CI

on:
  pull_request:
  push:
    branches:
      - main

jobs:
  ci:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - run: npm ci

    - run: npm run test

    # - run: npm run lint

    - run: npm run build

  publish:
    runs-on: ubuntu-latest
    steps:

    - uses: actions/checkout@v2

    - run: npm ci

    - run: npm run build

    # Ensure dist is built, committed, and pushed
    - name: Build and commit
      if: ${{ github.event_name == 'push' && github.ref == 'refs/heads/main' }}
      run: |
        git config --global user.name "GitHub Actions"
        git config --global user.email 'github-actions@users.noreply.github.com'
        git add dist/
        git commit -m "chore: Update dist" || echo "No changes to commit"
        git push origin HEAD:main

    # Use GitHub App token because we want to trigger the versioning.yml workflow, and GITHUB_TOKEN can't trigger other workflows
    # Permissions:
    #   - Contents: Read & write
    #   - Metadata: Read-only
    #   - Pull requests: Read & write
    - name: Generate token
      if: ${{ github.event_name == 'push' && github.ref == 'refs/heads/main' }}
      id: generate_token
      uses: tibdex/github-app-token@v1
      with:
        app_id: ${{ secrets.APP_ID }}
        private_key: ${{ secrets.PRIVATE_KEY }}

    - name: Release
      if: ${{ github.event_name == 'push' && github.ref == 'refs/heads/main' }}
      uses: google-github-actions/release-please-action@v2.7.0
      with:
        token: ${{ steps.generate_token.outputs.token }}
        release-type: node
        package-name: 'workflow-reports-action'
