name: Greetings

on: [pull_request, issues]

jobs:
  greeting:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/first-interaction@v1
      with:
        repo-token: ${{ secrets.GITHUB_TOKEN }}
        issue-message: 'Hello and welcome, new `issue` opener! Be sure to check out this project''s [Contributing Guidelines](https://github.com/imjohnbo/workflow-reports-action#contributing) as you wait for a response from the project''s maintainers.'
        pr-message: 'Hello and welcome, new `pull request`er! Be sure to check out this project''s [Contributing Guidelines](https://github.com/imjohnbo/workflow-reports-action#contributing) as you wait for a response from the project''s maintainers.'
