name: 'build-test'
on:
  workflow_dispatch:
    inputs:
      owner:
        description: 'Owner of actions to retrieve'
        required: true

jobs:
  build: # make sure build/ci work properly
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: ./
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          owner: ${{ github.event.inputs.owner }}
